# Generated by Django 5.1.7 on 2025-04-26 06:43

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poll_images/', validators=[polls.models.validate_image_size, polls.models.validate_image_extension], verbose_name='Изображение опроса'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[polls.models.validate_image_size, polls.models.validate_image_extension], verbose_name='Аватар'),
        ),
    ]
